Recipe-App
kambereBr/Recipe-App pull request #24
Opened 2023-11-17 17:20 UTC by Abdelaziz-Mahdi

### Project requirements

- [x] Login page and registration page:

- [x] Should be built with Devise.

- [x] Recipes list:

- Should display a list of recipes created by the logged-in user as in the wireframe.
- Should lead to recipe details.

- [x] Public recipe list:

- Should display a list of all public recipes ordered by newest as in the wireframe.
- Should lead to recipe details.

- If the user is the owner of the recipe, should allow the user to delete it.

- [x] Recipe details:

- Should display a toggle button that allows for a recipe to be made public or private.
- If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
- If the user is the owner of the recipe, should lead to the form that allows the user to add new food.

- [x] Make sure there are no N+1 queries happening.

- [x] Create a navigation menu that allows users to open all of the pages you created.

- [x] Write unit and integration tests

Only for a group that has less than 3 members:

- [x] Food list:

- Should display a list of food added by the logged-in user as in the wireframe (display also quantity of a given food).
- Should lead to a form that allows users to add new food.

- [x] General shopping list view:

- Should show the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
- Should count the total food items and total price of the missing food.

- If your team has 3 members these are requirements; otherwise, they are additional requirements

- [x] Inventories list:

- Should display a list of inventories created by the logged-in user as in the wireframe.
- Should lead to inventory details.
- If the user is the owner of the inventory, should allow to delete it.

- [x] Inventory details:

- Should display the inventory details as in the wireframe.
- Should lead to a form that allows users to add new food.

- [x] Recipe details:

- Should have a modal to choose an inventory to create a shopping list with, as in the wireframe.

- [x] Inventory shopping list:

- Should show the list of food that is missing by comparing the food in the recipe with the food in the inventory.
- Should count the total food items and total price of the missing food.

- [x] Technical setup

- Set up the repository on GitHub and use Gitflow.
- Set up Devise for authentication.
- Set up RSpec and Capybara testing libraries.

2023-11-17 20:07 UTC, Munsa1 requested changes
Hi @Abdelaziz-Mahdi @kambereBr @ahmed025566, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-11-17 20:07 UTC, Munsa1 commented on app/controllers/foods_controller.rb
> +end
- [ ] As per requirement only the User that created a food should be able to delete the food for security reasons. Currently, any user can do so. Kindly fix this issue.

Check the video below
[cinnamon-2023-11-17T204846+0200.webm](https://github.com/kambereBr/Recipe-App/assets/81932478/1f374d8c-4e51-4b36-87fb-71888b32d2ea)

2023-11-17 20:07 UTC, Munsa1 commented on app/controllers/recipes_controller.rb
> +end
- [ ] A user should only be able to delete a recipe if they are the owner which works okay. But, recipes created by a user are automatically seen under public recipes, kindly fix this.

Video demo
[cinnamon-2023-11-17T212218+0200.webm](https://github.com/kambereBr/Recipe-App/assets/81932478/41c77da2-cf86-4617-9779-1e790621ddf7)

2023-11-17 20:07 UTC, Munsa1 commented on app/views/recipes/show.html.erb
> +    </div>
- [ ] As per requirement on the recipe show page, you should be able to add an ingredient. You should be able to generate a shopping list that matches the given wireframe below

Wireframe
![image](https://github.com/kambereBr/Recipe-App/assets/81932478/3e68f1f2-cd1c-42b0-b906-88b92f27e07c)


The ingredients should be added to the recipe show page and not to the foods page. Clicking on the generate shopping list button should generate the shopping list in the above wireframe, kindly fix this


Video demo
[cinnamon-2023-11-17T213500+0200.webm](https://github.com/kambereBr/Recipe-App/assets/81932478/db0f2fdf-9782-4604-97b2-3879058177d9)

2023-11-17 20:07 UTC, Munsa1 commented on app/views/public_recipes/index.html.erb
> +</div>
- [ ] Kindly ensure only public recipes are being added to the public recipe section. Since all created recipes are currently being added there I have no way of telling


Video demo
[cinnamon-2023-11-17T214032+0200.webm](https://github.com/kambereBr/Recipe-App/assets/81932478/2693cd32-e694-473b-a833-48f6d1f7afc0)

2023-11-17 20:07 UTC, Munsa1 commented on app/views/recipes/show.html.erb
> +        </div>
- [ ] The recipe details should have a modal to choose an inventory to create a shopping list with, as in the given wireframe. Kindly add this feature as per the requirement for a team of 3 for the capstone

Wireframe
![image](https://github.com/kambereBr/Recipe-App/assets/81932478/320a29e7-c576-4a4e-a03c-b6b52a61bc24)

2023-11-17 20:07 UTC, Munsa1 commented on app/views/inventory_foods/new.html.erb
> +  <% end %>
- [ ] As per the requirements, the Inventory shopping list should achieve the following:

* Show the list of food that is missing by comparing the food in the recipe with the food in the inventory.
* Count the total food items and the total price of the missing food.

2023-11-18 02:53 UTC, ademibowale approved these changes
Hi @Abdelaziz-Mahdi @Munsa1 @kambereBr , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- The application has a login and Registration page, built with the Devise gem.✔️
- Recipe details page matches the given [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_food.png?raw=true)Recipe details page matches the given [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/images/recipe_food.png?raw=true)✔️
- Descriptive commit messages ✔️ 
- Clicking on a recipe item should lead to recipe details..✔️
- Good use of Gitflow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-18 03:04 UTC, merged